[package]
name = "week06"
version = "0.1.0"
authors = ["kilik <samuel_tsai@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
